// Generated by Melange
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function Add(Config) {
  var getIndexExn = Config.getIndexExn;
  var getIndex = function (index, ds) {
    try {
      return Caml_option.some(Curry._2(getIndexExn, index, ds));
    }
    catch (exn){
      return ;
    }
  };
  return {
          getIndex: getIndex,
          getIndexExn: getIndexExn
        };
}

exports.Add = Add;
/* No side effect */
