// Generated by Melange
'use strict';

var Exceptions = require("../Exceptions.bs.js");

function log2(u) {
  if (u < 0) {
    throw {
          RE_EXN_ID: Exceptions.Imaginary,
          _1: "log2",
          Error: new Error()
        };
  }
  if (u === 0) {
    throw {
          RE_EXN_ID: Exceptions.Undefined,
          _1: "log2",
          Error: new Error()
        };
  }
  var u$1 = u | (u >>> 1);
  var u$2 = u$1 | (u$1 >>> 2);
  var u$3 = u$2 | (u$2 >>> 4);
  var u$4 = u$3 | (u$3 >>> 8);
  var u$5 = u$4 | (u$4 >>> 16);
  var u$6 = (u$5 >>> 1);
  var u$7 = u$6 - ((u$6 >>> 1) & 1431655765) | 0;
  var u$8 = ((u$7 >>> 2) & 858993459) + (u$7 & 858993459) | 0;
  var u$9 = (u$8 >>> 4) + u$8 & 252645135;
  var u$10 = u$9 + (u$9 >>> 8) | 0;
  var u$11 = u$10 + (u$10 >>> 16) | 0;
  return u$11 & 63;
}

exports.log2 = log2;
/* No side effect */
