// Generated by Melange
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");

function make(param) {
  return [];
}

function length(prim) {
  return prim.length;
}

function isEmpty(arr) {
  return arr.length === 0;
}

var toList = $$Array.to_list;

var fromList = $$Array.of_list;

exports.make = make;
exports.length = length;
exports.isEmpty = isEmpty;
exports.toList = toList;
exports.fromList = fromList;
/* No side effect */
