// Generated by Melange
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Exceptions = require("../Exceptions.bs.js");

function make(param) {
  return /* [] */0;
}

function isEmpty(list) {
  if (list) {
    return false;
  } else {
    return true;
  }
}

function toList(list) {
  return list;
}

function fromList(list) {
  return list;
}

function getFirstExn(list) {
  if (list) {
    return list.hd;
  }
  throw {
        RE_EXN_ID: Exceptions.Empty,
        _1: "OCamlListCore.getFirstExn",
        Error: new Error()
      };
}

function addFirst(el, list) {
  return {
          hd: el,
          tl: list
        };
}

function dropFirstExn(list) {
  if (list) {
    return list.tl;
  }
  throw {
        RE_EXN_ID: Exceptions.Empty,
        _1: "OCamlListCore.dropFirstExn",
        Error: new Error()
      };
}

var length = List.length;

exports.make = make;
exports.length = length;
exports.isEmpty = isEmpty;
exports.toList = toList;
exports.fromList = fromList;
exports.getFirstExn = getFirstExn;
exports.addFirst = addFirst;
exports.dropFirstExn = dropFirstExn;
/* No side effect */
