// Generated by Melange
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var IndexOutOfBounds = /* @__PURE__ */Caml_exceptions.create("Exceptions.IndexOutOfBounds");

var NegativeIndex = /* @__PURE__ */Caml_exceptions.create("Exceptions.NegativeIndex");

var Empty = /* @__PURE__ */Caml_exceptions.create("Exceptions.Empty");

var UnexpectedNone = /* @__PURE__ */Caml_exceptions.create("Exceptions.UnexpectedNone");

var Imaginary = /* @__PURE__ */Caml_exceptions.create("Exceptions.Imaginary");

var Undefined = /* @__PURE__ */Caml_exceptions.create("Exceptions.Undefined");

var InternalError = /* @__PURE__ */Caml_exceptions.create("Exceptions.InternalError");

var NotEnoughElements = /* @__PURE__ */Caml_exceptions.create("Exceptions.NotEnoughElements");

var InvalidArguments = /* @__PURE__ */Caml_exceptions.create("Exceptions.InvalidArguments");

var EmptyRange = /* @__PURE__ */Caml_exceptions.create("Exceptions.EmptyRange");

exports.IndexOutOfBounds = IndexOutOfBounds;
exports.NegativeIndex = NegativeIndex;
exports.Empty = Empty;
exports.UnexpectedNone = UnexpectedNone;
exports.Imaginary = Imaginary;
exports.Undefined = Undefined;
exports.InternalError = InternalError;
exports.NotEnoughElements = NotEnoughElements;
exports.InvalidArguments = InvalidArguments;
exports.EmptyRange = EmptyRange;
/* No side effect */
