// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.bs.js");
var List = require("bs-platform/lib/js/list.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var HashtblWithChaining$Algorithms = require("../src/hashing/HashtblWithChaining.bs.js");

Jest.describe("Hashing With Chaining", (function (param) {
        var range_upto = function (n) {
          if (n !== 0) {
            return {
                    hd: n,
                    tl: range_upto(n - 1 | 0)
                  };
          } else {
            return /* [] */0;
          }
        };
        var keys = range_upto(400);
        var setup = function (param) {
          var hash = HashtblWithChaining$Algorithms.create((function (n) {
                  return n;
                }), (function (m, n) {
                  return Caml_int32.mod_(n, m);
                }));
          List.iter((function (key) {
                  return HashtblWithChaining$Algorithms.add(hash, key, String(key));
                }), keys);
          return hash;
        };
        Jest.test("length", (function (param) {
                var hash = setup(undefined);
                var length = HashtblWithChaining$Algorithms.length(hash);
                return Jest.Expect.toEqual(400, Jest.Expect.expect(length));
              }));
        Jest.test("find", (function (param) {
                var hash = setup(undefined);
                var result = List.map((function (key) {
                        return HashtblWithChaining$Algorithms.find(hash, key);
                      }), keys);
                var expected = List.map((function (key) {
                        return String(key);
                      }), keys);
                return Jest.Expect.toEqual(expected, Jest.Expect.expect(result));
              }));
        Jest.test("add", (function (param) {
                var hash = setup(undefined);
                HashtblWithChaining$Algorithms.add(hash, 17, "Hi");
                var e17 = HashtblWithChaining$Algorithms.find(hash, 17);
                return Jest.Expect.toEqual("Hi", Jest.Expect.expect(e17));
              }));
        Jest.test("remove restores the previous mapping", (function (param) {
                var hash = setup(undefined);
                HashtblWithChaining$Algorithms.add(hash, 17, "Hi");
                HashtblWithChaining$Algorithms.remove(hash, 17);
                var e17 = HashtblWithChaining$Algorithms.find(hash, 17);
                return Jest.Expect.toEqual("17", Jest.Expect.expect(e17));
              }));
        Jest.test("remove throws when the key doesn't exists", (function (param) {
                var hash = setup(undefined);
                HashtblWithChaining$Algorithms.remove(hash, 17);
                return Jest.Expect.toThrow(Jest.Expect.expect(function (param) {
                                return HashtblWithChaining$Algorithms.remove(hash, 17);
                              }));
              }));
        return Jest.test("hash table maintains its complete history", (function (param) {
                      var values = range_upto(400);
                      var hash = HashtblWithChaining$Algorithms.create((function (n) {
                              return n;
                            }), (function (m, n) {
                              return Caml_int32.mod_(n, m);
                            }));
                      List.iter((function (value) {
                              return HashtblWithChaining$Algorithms.add(hash, 17, value);
                            }), values);
                      var result = List.map((function (param) {
                              var value = HashtblWithChaining$Algorithms.find(hash, 17);
                              HashtblWithChaining$Algorithms.remove(hash, 17);
                              return value;
                            }), values);
                      var expected = List.rev(values);
                      return Jest.Expect.toEqual(expected, Jest.Expect.expect(result));
                    }));
      }));

/*  Not a pure module */
