// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.bs.js");
var KarpRabin$Algorithms = require("../src/hashing/KarpRabin.bs.js");

Jest.describe("Karp Rabin", (function (param) {
        Jest.test("search returns the start index of the pattern in the text when text has the pattern", (function (param) {
                var index = KarpRabin$Algorithms.search("Rabin", "OMG Karp Rabin works!");
                return Jest.Expect.toEqual(9, Jest.Expect.expect(index));
              }));
        return Jest.test("search returns None when the pattern is not in the text", (function (param) {
                      var index = KarpRabin$Algorithms.search("X", "OMG Karp Rabin works!");
                      return Jest.Expect.toEqual(undefined, Jest.Expect.expect(index));
                    }));
      }));

/*  Not a pure module */
